openapi: 3.2.0
info:
  title: Privado ID - Issuer Agent API
  description: 'The Issuer Node Core API is ideal for users who need multiple identities and for integrator profiles, who want to

    create solutions based on Privado ID functionalities and might be interested in having access to low level

    information such as Merkle Trees.'
  version: '1'
tags:
- name: Agent
  description: Collection of endpoints related to Mobile
paths:
  /v2/agent:
    post:
      summary: Agent
      operationId: Agent
      description: Identity Agent Endpoint
      tags:
      - Agent
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: jwz-token
      responses:
        '200':
          description: TBD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
  /v1/agent:
    post:
      summary: Agent V1
      operationId: AgentV1
      description: Identity Agent Endpoint for v1.
      deprecated: true
      tags:
      - Agent
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: jwz-token
      responses:
        '200':
          description: TBD
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AgentResponse'
        '400':
          $ref: '#/components/responses/400'
        '500':
          $ref: '#/components/responses/500'
components:
  responses:
    '400':
      description: Bad Request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorMessage'
    '500':
      description: Internal Server  error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorMessage'
  schemas:
    AgentResponse:
      $ref: '#/components/schemas/BasicMessage'
    GenericErrorMessage:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          example: Something happen
    BasicMessage:
      type: object
      required:
      - body
      - id
      - typ
      - type
      - thid
      - from
      - to
      properties:
        id:
          type: string
        typ:
          type: string
        type:
          type: string
        thid:
          type: string
        body:
          type: null
        from:
          type: string
        to:
          type: string
  securitySchemes:
    basicAuth:
      type: http
      scheme: basic
