openapi: 3.2.0
info:
  title: Privado ID Internal API
  description: Documentation for the Backend Verifier API
  version: '1'
tags:
- name: Internal
  description: Internal endpoints
paths:
  /:
    get:
      summary: Get the documentation
      operationId: GetDocumentation
      x-internal: true
      tags:
      - Internal
      responses:
        200:
          description: success and returns the documentation in HTML format
  /health:
    get:
      summary: Health Check
      operationId: Health
      tags:
      - Internal
      responses:
        '200':
          description: All services are running
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '500':
          $ref: '#/components/responses/500'
  /callback:
    post:
      summary: Callback
      operationId: Callback
      tags:
      - Internal
      parameters:
      - $ref: '#/components/parameters/sessionID'
      requestBody:
        required: true
        content:
          text/plain:
            schema:
              type: string
              example: jwz-token
              description: JWZ token
      responses:
        '200':
          description: Callback
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CallbackResponse'
        '404':
          $ref: '#/components/responses/404'
        '500':
          $ref: '#/components/responses/500'
components:
  parameters:
    sessionID:
      name: sessionID
      in: query
      required: true
      description: 'ID e.g: 89d298fa-15a6-4a1d-ab13-d1069467eedd

        '
      schema:
        type: string
        x-go-type: uuid.UUID
        x-go-type-import:
          name: uuid
          path: github.com/google/uuid
  schemas:
    GenericErrorMessage:
      type: object
      required:
      - message
      properties:
        message:
          type: string
          example: Something happen
    Health:
      type: object
      x-omitempty: false
      example:
        healthy: true
    CallbackResponse:
      type: object
  responses:
    '404':
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorMessage'
    '500':
      description: Internal Server error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/GenericErrorMessage'
